server:
  port: 9300
  display-name: DynamicDataSourceDemo

logging:
  level:
    root: info
    org.mybatis: debug
    org.springframework: warn
    org.springframework.jdbc: debug
    com.alibaba.druid: debug
    com.github.trang: debug

debug: false

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration
  aop:
    auto: true
    proxy-target-class: true
  http:
    encoding:
      enabled: true
      force: true
      charset: utf-8
    converters:
      preferred-json-mapper: gson
  mvc:
    servlet:
      load-on-startup: 1
    dateFormat: yyyy-MM-dd HH:mm:ss
#  jta:
#    atomikos:
#      datasource:
#        xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
#        unique-resource-name: 0


dynamic-data-source:
  druid:
    master:
      name: 1
      url: jdbc:mysql://10.33.106.239:3306/dynamic_master?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 1
      minIdle: 1
      maxActive: 10
    slave:
      name: 2
      url: jdbc:mysql://10.33.106.239:3306/dynamic_slave?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 1
      minIdle: 1
      maxActive: 10

mybatis:
  type-aliases-package: com.github.trang.dynamic.domain
  mapper-locations: classpath:mappers/*.xml
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

mapper:
  mappers:
    - com.github.trang.dynamic.util.BaseMapper
  not-empty: true
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  offset-as-page-num: true
  row-bounds-with-count: false
  page-size-zero: false
  reasonable: false
  support-methods-arguments: false
  auto-runtime-dialect: false